services:
  liiga:
    build: ./
    container_name: liiga
    volumes:
      - ./db:/usr/src/app/db
      - ./log:/usr/src/app/log
      - ./backup:/usr/src/app/backup
      - ./var:/usr/src/app/var
      - ./Game_CSV_files:/usr/src/app/Game_CSV_files
    env_file:
      - path: .env/default.env
        required: true # default
      - path: .env/service.env
        required: false
    restart: unless-stopped